# Generated by Django 6.0.5 on 2026-06-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0002_tienda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
