# Generated by Django 6.0.5 on 2026-06-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0003_tienda_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
