services:
  app:
    image: ghcr.io/jhonnikek/mercadoshop:latest
    container_name: app
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres_secure_pass_123@db:5432/mercadoshop
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=mercadoshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_secure_pass_123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
