services:
  app:
    build: .
    command:
      ["uv", "run", "python", "app/manage.py", "runserver", "0.0.0.0:8000"]
    container_name: app_dev
    ports:
      - "8000:8000"
    restart: "unless-stopped"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres_secure_pass_123@db:5432/mercadoshop
    volumes:
      - ./app:/code/app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db_dev
    restart: "unless-stopped"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=mercadoshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_secure_pass_123
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
