services:
  db:
    image: postgres:16-alpine
    container_name: mercadoshop_db
    environment:
      POSTGRES_DB: mercadoshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_pass_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mercadoshop"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: mercadoshop_web
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres_secure_pass_123@db:5432/mercadoshop
      - DEBUG=True
      - SECRET_KEY=django-insecure-$@e8repj499w)iee1sa3gchyn_p(q#ov6ame)b&#)u1b%ugbvy
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
