# Generated by Django 6.0.5 on 2026-05-31 20:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_dane', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TDepartamento',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclatura', models.CharField(max_length=255)),
                ('barrio', models.CharField(max_length=255)),
                ('notas_adicionales', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TDireccion',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TEstadoPedido',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'TRoles',
            },
        ),
        migrations.CreateModel(
            name='TiendaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TTiendaAdmin',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador de Plataforma'), ('TRABAJADOR', 'Trabajador de Tienda'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_admin', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('direccion_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_cliente', to='core.direccion')),
                ('rol_trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='core.rol')),
            ],
            options={
                'db_table': 'TUsuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TCarrito',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='core.categoria')),
            ],
            options={
                'db_table': 'TCategoria',
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_recibidor', models.CharField(max_length=255)),
                ('telefono_recibidor', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_entrega', to=settings.AUTH_USER_MODEL)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direccion')),
            ],
            options={
                'db_table': 'TDireccionCliente',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_dane', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.departamento')),
            ],
            options={
                'db_table': 'TMunicipio',
            },
        ),
        migrations.AddField(
            model_name='direccion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='core.municipio'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(max_length=255, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('costo_envio', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, max_digits=19)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('direccion_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direccioncliente')),
                ('estado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.estadopedido')),
            ],
            options={
                'db_table': 'TPedido',
            },
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_creador', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('numero_ticket', models.CharField(max_length=255, unique=True)),
                ('asunto', models.CharField(max_length=255)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs_creadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs', to='core.pedido')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs', to='core.tiendaadmin')),
            ],
            options={
                'verbose_name_plural': 'PQRS',
                'db_table': 'TPQRS',
            },
        ),
        migrations.CreateModel(
            name='HiloPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('tipo_actor', models.CharField(max_length=50)),
                ('es_mensaje_interno', models.BooleanField(default=False)),
                ('evidencia', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.pqrs')),
            ],
            options={
                'verbose_name': 'Hilo PQRS',
                'verbose_name_plural': 'Hilos PQRS',
                'db_table': 'THiloPQRS',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_corta', models.CharField(max_length=255)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('url_imagen_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('especificaciones', models.JSONField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=19)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.categoria')),
            ],
            options={
                'db_table': 'TProductos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_compra', models.DecimalField(decimal_places=4, max_digits=19)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
            ],
            options={
                'db_table': 'TDetallePedido',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_atencion', models.EmailField(max_length=255)),
                ('telefono_atencion', models.CharField(max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_tienda', models.CharField(max_length=50)),
                ('plan_id', models.IntegerField(blank=True, null=True)),
                ('fecha_vencimiento_suscripcion', models.DateTimeField(blank=True, null=True)),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direccion')),
            ],
            options={
                'db_table': 'TTiendas',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.tienda'),
        ),
        migrations.CreateModel(
            name='TransaccionPasarela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pasarela', models.CharField(max_length=255)),
                ('id_transaccion_externa', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(max_length=255)),
                ('franquicia', models.CharField(blank=True, max_length=50, null=True)),
                ('ultimos_4_digitos', models.CharField(blank=True, max_length=4, null=True)),
                ('cuotas', models.IntegerField(blank=True, null=True)),
                ('valor_transaccion', models.DecimalField(decimal_places=4, max_digits=19)),
                ('estado_transaccion', models.CharField(max_length=255)),
                ('codigo_aprobacion_banco', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.pedido')),
            ],
            options={
                'db_table': 'TTransaccionPasarela',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='transaccion_pasarela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asociados', to='core.transaccionpasarela'),
        ),
        migrations.CreateModel(
            name='TrabajadorTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='core.tienda')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_tienda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajador de Tienda',
                'verbose_name_plural': 'Trabajadores de Tiendas',
                'db_table': 'TTrabajadorTienda',
                'unique_together': {('tienda', 'trabajador')},
            },
        ),
    ]
