# Generated by Django 6.0.5 on 2026-06-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrs',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='pqrs',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pqrs',
            name='tienda',
        ),
        migrations.DeleteModel(
            name='HiloPQRS',
        ),
        migrations.DeleteModel(
            name='PQRS',
        ),
    ]
