# Generated by Django 6.0.5 on 2026-06-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pqrs_creador_remove_pqrs_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='tiendas', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='categorias_interes',
            field=models.ManyToManyField(blank=True, related_name='clientes_interesados', to='core.categoria'),
        ),
    ]
