name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: download code
        uses: actions/checkout@v4

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/jhonnikek/mercadoshop:latest

      - name: compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_IP }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          source: "compose.yml"
          target: "/home/ubuntu/projects/mercadoshop"

      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_IP }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /home/ubuntu/projects/mercadoshop
            docker compose pull
            docker compose up -d
